### ISSUE TITLE
Bombs break FAR

### ISSUE THREAD

**Issue by dawixx** [BahamutoD/BDArmory#10]
It seems that attaching any bomb to a plane whilst using Ferram Aerospace Research renders the plane useless( no lift, drag etc.). The craft returns to normal after jettisoning them. Any other munitions are working fine.

**Comment by dawixx** [comment]
It seemed to me that "dragModelType" set to none in part's cfg was causing the problem. I changed it to default for both mk82's and JDAM and it does solve the problem to a certain extent. The problem persists when there are more munitions attached. I started with 8 JDAM's and the craft's lift was NaN untill i jettisoned 5 of them. It came back to normal afterwards.

Edit:
After some further inspection it seems that those errors are being caused by other mods, I did a clean install with BDA and FAR and everything seemed fine.

**Comment by BahamutoD** [comment]
Fixed in the latest versions of BDArmory and FAR
