### ISSUE TITLE
The Weight of AN/M2 machinegun

### ISSUE THREAD

**Issue by DracheTek** [BahamutoD/BDArmory#14]
I noticed that the weight of AN/M2 machinegun is 0.28, but data shows that standard M2 machinegun weighs 0.038t (38kg) without attached mechanism. I doubt if it is a mistake of decimal point. It matters less when building modern aircraft but when building WWII crafts it became a problem.

**Comment by BahamutoD** [comment]
Thanks, this will be fixed in the update.
