### ISSUE TITLE
TWS Radar will not lock in guard mode

### ISSUE THREAD

**Issue by CommandMan7** [BahamutoD/BDArmory#18]
The TWS Radar does not properly work in guard mode, this issue has been encountered not only by me but also people in the steam group. It might take me a while to check github for a response, so you can PM me on steam instead, username is CommandMan7.

**Comment by CommandMan7** [comment]
It actually appears, with further testing, a lot of radar is broken. I can't get any sort of air to ground detection, or lock, of any type.

**Comment by BahamutoD** [comment]
Radar received a huge update in v0.10.0, so try it out.
