### ISSUE TITLE
DMG_MULTIPLIER is probably too high

### ISSUE THREAD

**Issue by ferram4** [BahamutoD/BDArmory#20]
Testing by @tetryds and his relatively realistic BAD-T pack indicates that the bullet damage multiplier should probably be reduced.  The current value of 500 results in .50 cal / 13mm bullets with proper data hitting like 20mm cannons.  I would suggest a drop to 100-150, which should keep the damage values far more sane, at least as a stop-gap.

**Comment by tetryds** [comment]
Further testing showed that a value of 50~100 is satisfactory when testing Aviator Arsenal v1.1 dev.
I recommend a value of ~70, and not higher than 125.

**Comment by BahamutoD** [comment]
Compromise at 100 then?

**Comment by tetryds** [comment]
Let me test all weapons (inc yours) with 100, just to make sure it's not too high.

**Comment by tetryds** [comment]
I have tested, and 100 seems fine, weapons are a bit strong but nothing unbalanced, a light fighter falls with two to three 20mm hits, 5 .50cal hits and not that many 7mm hits.
