### ISSUE TITLE
GPS Target Persistence?

### ISSUE THREAD

**Issue by TangentFoxy** [BahamutoD/BDArmory#28]
I would like to be able to fly a recon mission where I select GPS targets, then fly another mission where I attack those targets, but it seems that GPS targets don't persist. Could be get GPS target persistence?

**Comment by BahamutoD** [comment]
The GPS targets are persistent.  Did you save the game before/during ending the recon flight?

**Comment by TangentFoxy** [comment]
The vessel I was flying was destroyed, then I left, making sure the game was saved ("Space Center" button not yellow/orange). Could the vessel being destroyed have erased it?

I was imagining it as the data being transmitted back to base live..but yea, if that's why.. :(

**Comment by BahamutoD** [comment]
The vessel being destroyed shouldn't erase the data.  Were there any errors in the logs that may indicate that saving the GPS data failed?  Could you try just launching a vessel, acquiring a gps coordinate, save, exit, return and see if it works?

**Comment by boomchacle** [comment]
did the vessel that you were using  on the second run a different team than the first one? The gps coordinates will not go through teams.

**Comment by TangentFoxy** [comment]
I'm sorry, I completely forgot to test this. I'll set something to remind
me.

**Comment by boomchacle** [comment]
so did it work Guard?

**Comment by TangentFoxy** [comment]
I am terrible at keeping track of things sometimes. Still, I finally got to it.

Steps:
1. Launch craft on Team A.
2. Launch craft on Team B.
3. Send GPS from FLIR targeting ball.
4. Blow up first craft.
5. Blow up second craft.
6. Return to space center.
7. Launch craft on Team B.

And state was saved properly. Sooo... I probably reverted the first time and didn't realize I did, sorry. :/
