### ISSUE TITLE
Bug with salvo mode: If trigger is armed, salvo mode only fires a shot or two

### ISSUE THREAD

**Issue by allmhuran** [BahamutoD/BDArmory#30]
If guns are set to salvo mode, and the trigger is set to armed, then the guns will only fire once or twice while the trigger is held down. Barrage mode is OK regardless of whether the trigger is armed, and so is salvo mode if the trigger is not armed.

**Comment by allmhuran** [comment]
Update: This only happens if the weapons are selected by "next weapon" and "previous weapon". If I use a specific action group to enable both weapons in a pair, then they continue to fire normally even if the trigger state is "armed".

I found this while trying to see if I could fire different weapons with different buttons. I determined that I can't fire with different buttons but can toggle with different buttons and then fire using the normal trigger button.

**Comment by boomchacle** [comment]
Wait where are the salvo and barrage modes in the GUI?

**Comment by Shuudoushi** [comment]
Off topic, but when the hell did github get a 'reaction' option?

Any who @boomchacle, when you select a gun or other turret, you now have some options in the same spot as the ripple option for bombs/other munition.

**Comment by boomchacle** [comment]
Oh hey its allmhuran. I didn't even notice lol. I cant get the robotics mod to be so stable...

**Comment by allmhuran** [comment]
As stable as my mechs you mean? No, I expect not... these are the result of literally about 200 hours of tweaking the parts and the control program, plus another 200 on the geometry. This probably isn't the best place to discuss but if you want some help send me a message via reddit or gmail or something.

**Comment by boomchacle** [comment]
Yeah I just cant get them to oscillate back and forth
