### ISSUE TITLE
[Feature Request] Replays

### ISSUE THREAD

**Issue by KAmaia** [BahamutoD/BDArmory#37]
Been shooting a bunch of dogfights recently....A LOT OF DOGFIGHTS.

However, I've noticed that I'll miss some good action watching a _boring_ pilot doing his or her thing.  So I'm wondering, would it be possible to hook into BDArmory somehow have it record replays that could then be replayed using the BD mod?  

This would be great for cappers like me =D
Thanks!
Krystal

**Comment by Shuudoushi** [comment]
https://github.com/BahamutoD/CameraTools

This request will be better served on that repo ^

**Comment by KAmaia** [comment]
MOVED
