### ISSUE TITLE
missiles wont fire

### ISSUE THREAD

**Issue by Isenderen** [BahamutoD/BDArmory#53]
The missiles and bombs wont fire when using the hot key "fire missiles" bind from the weapon manager.

Software versions: KSP: 1.1.2 (Win64) - Unity: 5.2.4f1 - OS: Windows 10  (10.0.0) 64bit
Mods:
Toolbar - 1.7.12
B9 Animation Modules - 1.0.2
B9 Part Switch - 1.4.1
B9 Aerospace - 6.1.1
B9 Aerospace Procedural Parts - 0.40.2
Custom Asteroids - 1.3.1
Firespitter - 7.2.4
RasterPropMonitor - 0.26
KSP-AVC Plugin - 1.1.6.1
Docking Port Alignment Indicator - 6.4
RemoteTech - 1.7
Kerbal Alarm Clock - 3.6.3

Github wont allow .log files to be uploaded so im switching the extension to .txt just switch it back to .log when looking at it.
[KSP.txt](https://github.com/BahamutoD/BDArmory/files/311336/KSP.txt)

**Comment by boomchacle** [comment]
have you selected the missiles first? they wont fire unless they know which one to fire.

**Comment by boomchacle** [comment]
and by that, I mean with the hotkey that says switch or change weapon.

**Comment by Isenderen** [comment]
Sorry, this is fixed. I got some help from a Facebook group. I just forgot to close the issue.
